# Generated by Django 2.2.4 on 2022-03-20 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=100)),
                ('calorie', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('quantity', models.IntegerField(blank=True, default=1, null=True)),
                ('date_eaten', models.DateField(auto_now_add=True, null=True)),
                ('meal_type', models.ManyToManyField(to='tracker_app.MealType')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker_app.Profile')),
            ],
        ),
        migrations.DeleteModel(
            name='FoodList',
        ),
    ]
